# Numpy Array Operations


### Here you can read about some important Numpy functions.


- array(): Creates a numpy array from given data.
- arange(): Similar to range() in base Python but it returns numpy arrays and have much more features.
- vstack(): Stacks 2 or more arrays/lists vertically.
- reshape(): Reshapes a list/numpy array without changing the data or [row-wise] order.
- dot(): Returns the matrix product of 2 matrices.

**Note:** The naming convention used is, that if a variable is named _f1_ex2_some_name_, that means it is a part of example 2 of function 1.



In [ ]:
!pip install jovian --upgrade -q

In [1]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [3]:
# List of functions explained 
function1 = np.array
function2 = np.arange
function3 = np.vstack
function4 = np.reshape
function5 = np.dot

## Function 1 - np.array()

Returns the given data [usually a list or tuple] in form of numpy array

In [4]:
# Example 1 - Creating a numpy array from Python List
f1_ex1_python_list = [[1, 2, 3], [4, 5, 6]]

print('Initial data: ', f1_ex1_python_list)
print('Type of initial data: ', type(f1_ex1_python_list))

print()

f1_ex1_numpy_array = np.array(f1_ex1_python_list)

print('Data parsed from np.array() function: ', f1_ex1_numpy_array)
print('Type of data parsed from np.array() function: ', type(f1_ex1_numpy_array))

Initial data:  [[1, 2, 3], [4, 5, 6]]
Type of initial data:  <class 'list'>

Data parsed from np.array() function:  [[1 2 3]
 [4 5 6]]
Type of data parsed from np.array() function:  <class 'numpy.ndarray'>


**In the above example, the function np.array() takes in data in form of Python list and returns the same data in form of a numpy array.**

In [5]:
# Example 2 - Specifying datatype of the resulting array
f1_ex2_python_list = [[7, 8, 9], [10, 11, 12]]

print('First element of first row of Python list: ', f1_ex2_python_list[0][0])
print('Type of first element of first row of Python list: ', type(f1_ex2_python_list[0][0]))

print()

f1_ex2_numpy_array = np.array(f1_ex2_python_list, dtype = 'float64')

print('First element of first row of numpy array: ', f1_ex2_numpy_array[0][0])
print('Type of first element of first row of numpy array: ', type(f1_ex2_numpy_array[0][0]))

First element of first row of Python list:  7
Type of first element of first row of Python list:  <class 'int'>

First element of first row of numpy array:  7.0
Type of first element of first row of numpy array:  <class 'numpy.float64'>


**In the above example, even if the source data is a list of integers, the resultant numpy array is of datatype float as given explicitly in the np.array() function.**

In [6]:
# Example 3 - It gives VisibleDeprecationWarning when the the number of columns is not same in all rows.
f1_ex3_python_list = [[13, 14, 15], [16, 17, 18, 19]]

print('Initial data: ', f1_ex3_python_list)
print('Type of initial data: ', type(f1_ex3_python_list))

print()

f1_ex3_numpy_array = np.array(f1_ex3_python_list)

print('Data parsed from np.array() function: ', f1_ex3_numpy_array)
print('Type of data parsed from np.array() function: ', type(f1_ex3_numpy_array))

Initial data:  [[13, 14, 15], [16, 17, 18, 19]]
Type of initial data:  <class 'list'>

Data parsed from np.array() function:  [list([13, 14, 15]) list([16, 17, 18, 19])]
Type of data parsed from np.array() function:  <class 'numpy.ndarray'>


<ipython-input-6-1b033f15f21a>:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  f1_ex3_numpy_array = np.array(f1_ex3_python_list)


**As we see in the above examples, number of columns [number of elements in a row] should be same for each row. To solve, we can append a null value to the row(s) with less number of elements(comumns) than others.**

In [7]:
# Example 4 - alternative way to avoid the exception
f1_ex4_python_list_alt = [[13, 14, 15, None], [16, 17, 18, 19]]

print('Initial data: ', f1_ex4_python_list_alt)
print('Type of initial data: ', type(f1_ex4_python_list_alt))

print()

f1_ex4_numpy_array_alt = np.array(f1_ex4_python_list_alt)

print('Data parsed from np.array() function: ', f1_ex4_numpy_array_alt)
print('Type of data parsed from np.array() function: ', type(f1_ex4_numpy_array_alt))

Initial data:  [[13, 14, 15, None], [16, 17, 18, 19]]
Type of initial data:  <class 'list'>

Data parsed from np.array() function:  [[13 14 15 None]
 [16 17 18 19]]
Type of data parsed from np.array() function:  <class 'numpy.ndarray'>


**Above method is just a way to avoid the exception, it may or may not support your particular use-case.**

In [ ]:
jovian.commit()

## Function 2 - np.arange()

Returns an numpy array of evenly spaced numbers with given dimensions.

In [8]:
# Example 1 - Creating an array of even numbers between 0 [inclusive] and 20 [exclusive] [Starting from 0]

f2_ex1_first_ten_even_numbers = np.arange(start = 0, stop = 20, step = 2)

print('A list of first 10 even numbers created by np.arange():')
print(f2_ex1_first_ten_even_numbers)

A list of first 10 even numbers created by np.arange():
[ 0  2  4  6  8 10 12 14 16 18]


**In the above example, 'start' will be the first element of the array and 'step' is the common difference between any 2 adjacent elements.**

**The resultant array will contain numbers which are strictly smaller than the 'stop' parameter.**

In [9]:
# Example 2 - We can also give a negative step

f2_ex2_even_numbers_in_descending_order = np.arange(start = 20, stop = 0, step = -2)

print('Array of even number between 0 and 20 in descending order:')
print(f2_ex2_even_numbers_in_descending_order)

Array of even number between 0 and 20 in descending order:
[20 18 16 14 12 10  8  6  4  2]


**We can see that now 20 in included in the result while 0 is not.**

In [10]:
# Example 3 - It will return an empty array if start is smaller than stop and step is negative.

f1_ex3_first_ten_even_numbers = np.arange(start = 0, stop = 20, step = -2)

print('As we give a negative step when start is smaller than stop, we get:')
print(f1_ex3_first_ten_even_numbers)

As we give a negative step when start is smaller than stop, we get:
[]


**As we can see, if adding step to start doesn't decrease the absolute difference between the start and stop, there will be an infinitely long list if we start calculating the result without checking this case.**

**To avoid this, we should always check this special case before calling the function as it does not throw an exception in this case, we are prone to logical errors here.**

**We can use this function in use-case like where we need a list of first 10 whole numbers, first 5 multiples of 3, etc. as by using this, we'll not have to write a loop for these use-cases.**

In [ ]:
jovian.commit()

## Function 3 - np.vstack()

Concatenates the given arrays along the first axis ie along the columns.

In [11]:
# Example 1 - Concatenating two Python lists
f3_ex1_list1 = [1, 3, 5]
f3_ex1_list2 = [7, 9, 10]

print('Individual array are: ')
print(f3_ex1_list1)
print(f3_ex1_list2)

f3_ex1_stacked_array = np.vstack((f3_ex1_list1, f3_ex1_list2))

print('\n\nConcatenated array is: ')
print(f3_ex1_stacked_array)

Individual array are: 
[1, 3, 5]
[7, 9, 10]


Concatenated array is: 
[[ 1  3  5]
 [ 7  9 10]]


**We need to pass the tuple containing all the arrays [numpy arrays or python lists] and it will return those stacked along columns.**

In [12]:
# Example 2 - Concatenating 2 - Dimensional numpy lists.

f3_ex2_ndarray_1 = np.array([[1, 2, 3], [4, 5, 6]])
f3_ex2_ndarray_2 = np.array([[7, 8, 9], [10, 11, 12]])

print('Individual array are: ')
print(f3_ex2_ndarray_1)
print(f3_ex2_ndarray_2)

f3_ex2_concatenated_array = np.vstack((f3_ex2_ndarray_1, f3_ex2_ndarray_2))

print('\n\nConcatenated array is: ')
print(f3_ex2_concatenated_array)

Individual array are: 
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Concatenated array is: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**As depicted, we can stack any two arrays with equal number of columns.**

In [13]:
# Example 3 - It throws error when the number of columns is not consistent along all the given arrays.

f3_ex3_ndarray_1 = np.array([[1, 2, 3], [4, 5, 6]])
f3_ex3_ndarray_2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

print('Individual array are: ')
print(f3_ex3_ndarray_1)
print(f3_ex3_ndarray_2)

f3_ex3_concatenated_array = np.vstack((f3_ex3_ndarray_1, f3_ex3_ndarray_2))

print('\n\nConcatenated array is: ')
print(f3_ex3_concatenated_array)

Individual array are: 
[[1 2 3]
 [4 5 6]]
[[ 7  8  9 10]
 [11 12 13 14]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

**Above exception can be avoided using same trick as given in Example 4 of function 1.**

**It is just a particular case of the more general np.concatenate() function. Using this function instead increases the code readability and decreases the amount of parameters needed to be given as input.**

In [ ]:
jovian.commit()

## Function 4 - np.reshape()

It takes input a Python list or a numpy array and returns another numpy array object with same data but with different shape.

In [14]:
# Example 1 - Let's try converting a 4 x 3 array to a 2 x 6 array

f4_ex1_4x3_numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print('Initial 4 x 3 array:')
print(f4_ex1_4x3_numpy_array)

f4_ex1_2x6_reshaped_array = np.reshape(f4_ex1_4x3_numpy_array, newshape = (2, 6))

print('\n\nReshaped 2 x 6 array:')
print(f4_ex1_2x6_reshaped_array)

Initial 4 x 3 array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshaped 2 x 6 array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**As stated in the definition, it returns the same data, but in different order.**

In [15]:
# Example 2 - Another common use case of this function is to generate a desired 2D array from a 1D array. Let's see

f4_ex2_1d_python_array = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]

print('Initial 1D Python list:')
print(f4_ex2_1d_python_array)

f4_ex2_4x3_reshaped_array = np.reshape(f4_ex2_1d_python_array, newshape = (4, 3))

print('\n\nReshaped 4 x 3 numpy array:')
print(f4_ex2_4x3_reshaped_array)

Initial 1D Python list:
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]


Reshaped 4 x 3 numpy array:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


**Explanation about example**

In [16]:
''' Example 3 - It returns a ValueError exception when the number of elements in the given array is not equal to 
    the number of elements in an array of desired shape.'''

f4_ex3_2x2_numpy_array = np.array([[5, 15], [25, 35]])

print('Initial 2 x 2 array:')
print(f4_ex3_2x2_numpy_array)

print("First let's try converting the given array to a 4 x 1 array")
f4_ex3_4x1_reshaped_array = np.reshape(f4_ex3_2x2_numpy_array, newshape = (4, 1))

print('\n\nReshaped 4 x 1 array:')
print(f4_ex3_4x1_reshaped_array)

print("Now let's try converting the same array to a 4 x 4 array")
f4_ex3_4x4_reshaped_array = np.reshape(f4_ex3_2x2_numpy_array, newshape = (4, 4))

print('\n\nReshaped 4 x 4 array:') # This line is never going to run
print(f4_ex3_4x4_reshaped_array)

Initial 2 x 2 array:
[[ 5 15]
 [25 35]]
First let's try converting the given array to a 4 x 1 array


Reshaped 4 x 1 array:
[[ 5]
 [15]
 [25]
 [35]]
Now let's try converting the same array to a 4 x 4 array


ValueError: cannot reshape array of size 4 into shape (4,4)

**As you might have already figured out, if we want an array of size 4 x 4, we must input an array in which the number of elements is exactly equal to 16.**

**One important point to notice is that in most cases, it will not change the underlying object and the input and output arrays will just be different views of the same object**

In [ ]:
jovian.commit()

## Function 5 - np.dot()

Used to calculate the matrix product of 2 matrices [matrices can be Python lists or numpy arrays]

In [17]:
# Example 1 - Let's calculate the matrix product of two 2D numpy arrays

f5_ex1_array_1 = np.array([[1, 2], [3, 4]])
f5_ex1_array_2 = np.array([[5, 6], [7, 8]])

print('Array 1 is:')
print(f5_ex1_array_1)

print('Array 2 is:')
print(f5_ex1_array_2)

f5_ex1_matrix_product = np.dot(f5_ex1_array_1, f5_ex1_array_2)

print('\n\nProduct matrix as calculated by np.dot function:')
print(f5_ex1_matrix_product)

Array 1 is:
[[1 2]
 [3 4]]
Array 2 is:
[[5 6]
 [7 8]]


Product matrix as calculated by np.dot function:
[[19 22]
 [43 50]]


**As expected, it returns the matrix product of two given arrays.**

In [18]:
# Example 2 - It can also be used to multiply matrices with scalers.

f5_ex2_some_int = 5
f5_ex2_2x2_array = np.array([[9, 10], [11, 12]])

print("Let's take a sample matrix:")
print(f5_ex2_2x2_array)

f5_ex2_dot_product = np.dot(f5_ex2_some_int, f5_ex2_2x2_array)

print('\n\nAs we try to myltiply a scalar valued {} by the above matrix, we get:'.format(f5_ex2_some_int))
print(f5_ex2_dot_product)

Let's take a sample matrix:
[[ 9 10]
 [11 12]]


As we try to myltiply a scalar valued 5 by the above matrix, we get:
[[45 50]
 [55 60]]


**Here, the function multiplies each element of the matrix with the given scalar.**

In [19]:
''' Example 3 - It throws ValueError when the last dimension of the first matrix 
    is not same as the first dimension of second matrix.'''

f5_ex3_array_1 = np.array([[10, 11], [12, 13]])
f5_ex3_array_2 = np.array([[14, 15], [16, 17], [18, 19]])

print('Shape of array 1 is:')
print(f5_ex3_array_1.shape)

print('Shape of array 2 is:')
print(f5_ex3_array_2.shape)

print('\nAs we already know, multiplying these matrixes is against the rules of matrix multiplication.')
print("Still let's try multiplying them through np.dot()")

f5_ex3_matrix_product = np.dot(f5_ex3_array_1, f5_ex3_array_2)

print('\n\nProduct matrix as calculated by np.dot function:')
print(f5_ex3_matrix_product)

Shape of array 1 is:
(2, 2)
Shape of array 2 is:
(3, 2)

As we already know, multiplying these matrixes is against the rules of matrix multiplication.
Still let's try multiplying them through np.dot()


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

**Since this exception usually occurrs due to logical abnormalities, it is recommended not to except it in error handling as the exception can help you to easily identify the issue in the logic**

**Numpy is a very important library in Data Analysis and hence if one aspires to become a Data Analyst or Data Scientist, Numpy should be studied thoroughly.**

In [ ]:
jovian.commit()

## Conclusion

This was my introduction to Numpy functions. Comments are welcome.

## Reference Links


* Numpy Documentation Homepage: https://numpy.org/doc/stable/user/quickstart.html
* Numpy Cheatsheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
* Numpy GitHub Repo [Here you can see the source code of all the Numpy function]: https://github.com/numpy/numpy

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "parresh77/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/parresh77/numpy-array-operations


'https://jovian.ai/parresh77/numpy-array-operations'

In [ ]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "parresh77/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
